name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.get_version.outputs.VERSION}}
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

  release:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 16
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Drevision=${{needs.get_version.outputs.version}}
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: get_version
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: <username>/<app>:latest,<username>/<app>:${{needs.get_version.outputs.version}}
